### ISSUE TITLE
Keeeeeep R6 strong & great !!

### ISSUE THREAD

**Issue by SilverUnicorn** [FanSolomon/booking-centre#1]
All rigth, the title is just a meme, just forget it... I just wanna see how far this project can go with ur game passion XD
U got this !! !
May the force be with you XD

**Comment by FanSolomon** [comment]
Thanks bro!!! I hope so. ;D Thanks again for your encouragement!

**Comment by FanSolomon** [comment]
> All rigth, the title is just a meme, just forget it... I just wanna see how far this project can go with ur game passion XD
> U got this !! !
> May the force be with you XD

Thanks bro!!! I hope so. ;D Thanks again for your encouragement!
